//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int idc { get; set; }
        public string Nombrec { get; set; }
        public string emailc { get; set; }
        public string telefonoc { get; set; }
        public string mensajec { get; set; }
    }
}
